[default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
sender = '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266'
tx_origin = '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266'
# See more config options https://github.com/gakonst/foundry/tree/master/config